# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
    jms_serializer.naming_strategy:
        alias: jms_serializer.identical_property_naming_strategy
