<?php
/**
 * Created by PhpStorm.
 * User: Daedalus
 * Date: 20/03/2018
 * Time: 20:52
 */

namespace Tests\ApiBundle\Entity;

use ApiBundle\Entity\User;
use PHPUnit\Framework\TestCase;

class UserTest extends TestCase
{
    /**
     * @var User
     */
    private $oUser;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->oUser = new User();
    }

    public function testGetUsername()
    {
        $test = 'TestUsername';
        $this->oUser->setUsername($test);
        $this->assertEquals($test, $this->oUser->getUsername());
    }

    public function testGetSalt()
    {
        $this->assertEquals(null, $this->oUser->getSalt());
    }

    public function testSetPassword()
    {
        $this->assertEquals(null, $this->oUser->getSalt());
    }

    public function testGetPassword()
    {
        $this->assertEquals(null, $this->oUser->getSalt());
    }

    public function testGetRoles()
    {
        $this->assertEquals(null, $this->oUser->getSalt());
    }

    public function testEraseCredentials()
    {
        $this->assertEquals(null, $this->oUser->getSalt());
    }

    public function testSerialize()
    {
        $this->assertEquals(null, $this->oUser->getSalt());
    }

    public function testUnserialize()
    {
        $this->assertEquals(null, $this->oUser->getSalt());
    }

    public function testGetId()
    {
        $this->assertEquals(null, $this->oUser->getSalt());
    }
}
