<?php

namespace ApiBundle\Repository;

/**
 * MappingNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MappingNodeRepository extends \Doctrine\ORM\EntityRepository
{
}
