<?php

namespace ApiBundle\Repository;

/**
 * MappingNodeAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MappingNodeAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
